// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClrraA6bFAi2j3vzyGXBr6itSK5t_RR30',
    appId: '1:588187581127:web:a4d840a7bdb652b5375ce2',
    messagingSenderId: '588187581127',
    projectId: 'busybees-132f3',
    authDomain: 'busybees-132f3.firebaseapp.com',
    storageBucket: 'busybees-132f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArL0gyqzrGLik1UysNZTfXkGF8tHnWtmk',
    appId: '1:588187581127:android:e94e9d6896495661375ce2',
    messagingSenderId: '588187581127',
    projectId: 'busybees-132f3',
    storageBucket: 'busybees-132f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3G-90NRo7-fJPJq6v5C6Xqa4Z9xatZw',
    appId: '1:588187581127:ios:a63a0a032c6f4dfa375ce2',
    messagingSenderId: '588187581127',
    projectId: 'busybees-132f3',
    storageBucket: 'busybees-132f3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3G-90NRo7-fJPJq6v5C6Xqa4Z9xatZw',
    appId: '1:588187581127:ios:a63a0a032c6f4dfa375ce2',
    messagingSenderId: '588187581127',
    projectId: 'busybees-132f3',
    storageBucket: 'busybees-132f3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClrraA6bFAi2j3vzyGXBr6itSK5t_RR30',
    appId: '1:588187581127:web:3d3b28a155804a75375ce2',
    messagingSenderId: '588187581127',
    projectId: 'busybees-132f3',
    authDomain: 'busybees-132f3.firebaseapp.com',
    storageBucket: 'busybees-132f3.appspot.com',
  );
}
